config/routes.rb
Rails.application.routes.draw do

	root 'entries#index'

	resources :entries 
	resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

	has_many :taggings
	has_many :tags, through: :taggings


	validates :title, presence: true
	validates :link, presence: true

	def tag_list 
		tags.join(", ")
	end

	def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end

end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :entries, through: :taggings

	validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	def index 
		@entries = Entry.all 
		@tags = Tag.all
	end

  def show
    @entry = Entry.find(params[:id])
  end

	def scrape

    RedditScrapper.scrape

    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entries were successfully scraped.' }
      format.json { entriesArray.to_json }
    end
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all 
	end
	
	def show 
		@tag = Tag.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/entries/index.html.erb
<div class="column">
  <h1>Reddit's Scrapped Results</h1>
</div>

<div class="row">
  <div class="column column-80">
      <% @entries.reverse.each do |entry| %>
        <tr>
          <td>
            <h3><%= entry.title %></h3>
            <p><%= entry.link %></p>
          </td>
        </tr>
      <% end %>
  </div>

  <div class="column column-20">
    <h3>Tags:</h3>
     <% @tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <% end %>
  </div>
</div>

app/views/entries/show.html.erb
 <div class="row">
    <div class="column">
			<h3><%= @entry.title %></h3>
  	</div>
  </div>

  <div class="row">
    <div class="column">
			<h5>Link: <%= @entry.link %></h5>
  	</div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrapyTags</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<!-- Google Fonts -->
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">

<!-- CSS Reset -->
<link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">

<!-- Milligram CSS minified -->
<link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">

<!-- You should properly set the path from the main file. -->
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tags/show.html.erb
<div class="container">

<h1>Entries Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.entries.each do |entry| %>
    <li><%= link_to entry.title, entry_path(entry) %></li>
  <% end %>
</ul>


</div>